export const locales = ["en", "hi", "mr", "bn", "ta", "te", "gu", "pa", "ur", "es", "fr", "de", "ar", "zh", "ja", "ko"] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = "en";
export const rtlLocales = new Set<Locale>(["ar", "ur"]);

export const languageNames: Record<Locale, string> = {
  en: "English", hi: "हिन्दी", mr: "मराठी", bn: "বাংলা", ta: "தமிழ்",
  te: "తెలుగు", gu: "ગુજરાતી", pa: "ਪੰਜਾਬੀ", ur: "اردو", es: "Español",
  fr: "Français", de: "Deutsch", ar: "العربية", zh: "中文", ja: "日本語", ko: "한국어",
};

export function isLocale(value: unknown): value is Locale {
  return typeof value === "string" && locales.includes(value as Locale);
}

export function localeFromPathname(pathname: string): Locale | null {
  const segment = pathname.split("/")[1];
  return isLocale(segment) ? segment : null;
}

export function localizePath(pathname: string, locale: Locale) {
  if (!pathname.startsWith("/") || pathname.startsWith("/api/")) return pathname;
  const current = localeFromPathname(pathname);
  const rest = current ? pathname.slice(current.length + 1) || "/" : pathname;
  return `/${locale}${rest === "/" ? "" : rest}`;
}

export type Messages = { [Key in keyof typeof messages.en]: string };

export const messages = {
  en: { collections: "Collections", marketplace: "Marketplace", about: "About", assets: "Your Assets", upload: "Upload", support: "Queries & Feedback", moderate: "Moderate Uploads", signIn: "Sign In", signOut: "Sign Out", enterVr: "Enter VR", search: "Search artifacts", searchPlaceholder: "Search artifacts, materials, or collections…", searching: "Searching…", noResults: "No artifacts found.", account: "Museum member", mobileAccount: "Mobile account", language: "Language", closeMenu: "Close menu", openMenu: "Open menu", accountMenu: "Open account menu", signOutTitle: "Sign out of the museum?", signOutDescription: "Your cart and account data will remain safely stored for your next visit." },
  hi: { collections: "संग्रह", marketplace: "बाज़ार", about: "परिचय", assets: "आपकी संपत्तियाँ", upload: "अपलोड", support: "प्रश्न और प्रतिक्रिया", moderate: "अपलोड समीक्षा", signIn: "साइन इन", signOut: "साइन आउट", enterVr: "VR में जाएँ", search: "कलाकृतियाँ खोजें", searchPlaceholder: "कलाकृतियाँ, सामग्री या संग्रह खोजें…", searching: "खोज जारी है…", noResults: "कोई कलाकृति नहीं मिली।", account: "संग्रहालय सदस्य", mobileAccount: "मोबाइल खाता", language: "भाषा", closeMenu: "मेनू बंद करें", openMenu: "मेनू खोलें", accountMenu: "खाता मेनू खोलें", signOutTitle: "संग्रहालय से साइन आउट करें?", signOutDescription: "आपकी कार्ट और खाता जानकारी अगली यात्रा के लिए सुरक्षित रहेगी।" },
  mr: { collections: "संग्रह", marketplace: "बाजारपेठ", about: "आमच्याविषयी", assets: "तुमची मालमत्ता", upload: "अपलोड", support: "प्रश्न आणि अभिप्राय", moderate: "अपलोड परीक्षण", signIn: "साइन इन", signOut: "साइन आउट", enterVr: "VR मध्ये जा", search: "कलाकृती शोधा", searchPlaceholder: "कलाकृती, साहित्य किंवा संग्रह शोधा…", searching: "शोधत आहे…", noResults: "कलाकृती सापडल्या नाहीत.", account: "संग्रहालय सदस्य", mobileAccount: "मोबाइल खाते", language: "भाषा", closeMenu: "मेनू बंद करा", openMenu: "मेनू उघडा", accountMenu: "खाते मेनू उघडा", signOutTitle: "साइन आउट करायचे?", signOutDescription: "तुमची कार्ट आणि खाते माहिती सुरक्षित राहील." },
  bn: { collections: "সংগ্রহ", marketplace: "বাজার", about: "পরিচিতি", assets: "আপনার সম্পদ", upload: "আপলোড", support: "প্রশ্ন ও মতামত", moderate: "আপলোড পর্যালোচনা", signIn: "সাইন ইন", signOut: "সাইন আউট", enterVr: "VR-এ প্রবেশ", search: "নিদর্শন খুঁজুন", searchPlaceholder: "নিদর্শন, উপাদান বা সংগ্রহ খুঁজুন…", searching: "খোঁজা হচ্ছে…", noResults: "কোনো নিদর্শন পাওয়া যায়নি।", account: "জাদুঘর সদস্য", mobileAccount: "মোবাইল অ্যাকাউন্ট", language: "ভাষা", closeMenu: "মেনু বন্ধ করুন", openMenu: "মেনু খুলুন", accountMenu: "অ্যাকাউন্ট মেনু খুলুন", signOutTitle: "জাদুঘর থেকে সাইন আউট করবেন?", signOutDescription: "আপনার কার্ট ও অ্যাকাউন্ট তথ্য নিরাপদ থাকবে।" },
  ta: { collections: "தொகுப்புகள்", marketplace: "சந்தை", about: "அறிமுகம்", assets: "உங்கள் சொத்துகள்", upload: "பதிவேற்று", support: "கேள்விகள் மற்றும் கருத்து", moderate: "பதிவேற்ற மதிப்பாய்வு", signIn: "உள்நுழை", signOut: "வெளியேறு", enterVr: "VR-ல் நுழை", search: "கலைப்பொருட்களைத் தேடு", searchPlaceholder: "கலைப்பொருட்கள், பொருட்கள் அல்லது தொகுப்புகளைத் தேடுங்கள்…", searching: "தேடுகிறது…", noResults: "கலைப்பொருட்கள் கிடைக்கவில்லை.", account: "அருங்காட்சியக உறுப்பினர்", mobileAccount: "மொபைல் கணக்கு", language: "மொழி", closeMenu: "பட்டியை மூடு", openMenu: "பட்டியைத் திற", accountMenu: "கணக்கு பட்டியைத் திற", signOutTitle: "வெளியேற வேண்டுமா?", signOutDescription: "உங்கள் வண்டியும் கணக்கு தகவலும் பாதுகாப்பாக இருக்கும்." },
  te: { collections: "సేకరణలు", marketplace: "మార్కెట్", about: "గురించి", assets: "మీ ఆస్తులు", upload: "అప్‌లోడ్", support: "ప్రశ్నలు మరియు అభిప్రాయం", moderate: "అప్‌లోడ్ సమీక్ష", signIn: "సైన్ ఇన్", signOut: "సైన్ అవుట్", enterVr: "VRలోకి ప్రవేశించండి", search: "కళాఖండాలను వెతకండి", searchPlaceholder: "కళాఖండాలు, పదార్థాలు లేదా సేకరణలను వెతకండి…", searching: "వెతుకుతోంది…", noResults: "కళాఖండాలు కనుగొనబడలేదు.", account: "మ్యూజియం సభ్యుడు", mobileAccount: "మొబైల్ ఖాతా", language: "భాష", closeMenu: "మెను మూసివేయి", openMenu: "మెను తెరువు", accountMenu: "ఖాతా మెను తెరువు", signOutTitle: "సైన్ అవుట్ చేయాలా?", signOutDescription: "మీ కార్ట్ మరియు ఖాతా సమాచారం సురక్షితంగా ఉంటుంది." },
  gu: { collections: "સંગ્રહો", marketplace: "બજાર", about: "પરિચય", assets: "તમારી સંપત્તિ", upload: "અપલોડ", support: "પ્રશ્નો અને પ્રતિસાદ", moderate: "અપલોડ સમીક્ષા", signIn: "સાઇન ઇન", signOut: "સાઇન આઉટ", enterVr: "VRમાં જાઓ", search: "કલાકૃતિઓ શોધો", searchPlaceholder: "કલાકૃતિઓ, સામગ્રી અથવા સંગ્રહો શોધો…", searching: "શોધી રહ્યું છે…", noResults: "કોઈ કલાકૃતિ મળી નથી.", account: "સંગ્રહાલય સભ્ય", mobileAccount: "મોબાઇલ ખાતું", language: "ભાષા", closeMenu: "મેનૂ બંધ કરો", openMenu: "મેનૂ ખોલો", accountMenu: "ખાતા મેનૂ ખોલો", signOutTitle: "સાઇન આઉટ કરવું છે?", signOutDescription: "તમારી કાર્ટ અને ખાતાની માહિતી સુરક્ષિત રહેશે." },
  pa: { collections: "ਸੰਗ੍ਰਹਿ", marketplace: "ਬਾਜ਼ਾਰ", about: "ਜਾਣ-ਪਛਾਣ", assets: "ਤੁਹਾਡੀਆਂ ਸੰਪਤੀਆਂ", upload: "ਅੱਪਲੋਡ", support: "ਸਵਾਲ ਅਤੇ ਫੀਡਬੈਕ", moderate: "ਅੱਪਲੋਡ ਸਮੀਖਿਆ", signIn: "ਸਾਈਨ ਇਨ", signOut: "ਸਾਈਨ ਆਉਟ", enterVr: "VR ਵਿੱਚ ਜਾਓ", search: "ਕਲਾਕ੍ਰਿਤੀਆਂ ਖੋਜੋ", searchPlaceholder: "ਕਲਾਕ੍ਰਿਤੀਆਂ, ਸਮੱਗਰੀ ਜਾਂ ਸੰਗ੍ਰਹਿ ਖੋਜੋ…", searching: "ਖੋਜ ਜਾਰੀ ਹੈ…", noResults: "ਕੋਈ ਕਲਾਕ੍ਰਿਤੀ ਨਹੀਂ ਮਿਲੀ।", account: "ਅਜਾਇਬਘਰ ਮੈਂਬਰ", mobileAccount: "ਮੋਬਾਈਲ ਖਾਤਾ", language: "ਭਾਸ਼ਾ", closeMenu: "ਮੇਨੂ ਬੰਦ ਕਰੋ", openMenu: "ਮੇਨੂ ਖੋਲ੍ਹੋ", accountMenu: "ਖਾਤਾ ਮੇਨੂ ਖੋਲ੍ਹੋ", signOutTitle: "ਸਾਈਨ ਆਉਟ ਕਰਨਾ ਹੈ?", signOutDescription: "ਤੁਹਾਡੀ ਕਾਰਟ ਅਤੇ ਖਾਤਾ ਜਾਣਕਾਰੀ ਸੁਰੱਖਿਅਤ ਰਹੇਗੀ।" },
  ur: { collections: "مجموعے", marketplace: "بازار", about: "تعارف", assets: "آپ کے اثاثے", upload: "اپ لوڈ", support: "سوالات اور آراء", moderate: "اپ لوڈ جائزہ", signIn: "سائن ان", signOut: "سائن آؤٹ", enterVr: "VR میں جائیں", search: "نوادرات تلاش کریں", searchPlaceholder: "نوادرات، مواد یا مجموعے تلاش کریں…", searching: "تلاش جاری ہے…", noResults: "کوئی نوادرات نہیں ملے۔", account: "عجائب گھر کا رکن", mobileAccount: "موبائل اکاؤنٹ", language: "زبان", closeMenu: "مینو بند کریں", openMenu: "مینو کھولیں", accountMenu: "اکاؤنٹ مینو کھولیں", signOutTitle: "سائن آؤٹ کریں؟", signOutDescription: "آپ کی کارٹ اور اکاؤنٹ کی معلومات محفوظ رہیں گی۔" },
  es: { collections: "Colecciones", marketplace: "Mercado", about: "Acerca de", assets: "Tus recursos", upload: "Subir", support: "Consultas y comentarios", moderate: "Revisar cargas", signIn: "Iniciar sesión", signOut: "Cerrar sesión", enterVr: "Entrar en VR", search: "Buscar objetos", searchPlaceholder: "Buscar objetos, materiales o colecciones…", searching: "Buscando…", noResults: "No se encontraron objetos.", account: "Miembro del museo", mobileAccount: "Cuenta móvil", language: "Idioma", closeMenu: "Cerrar menú", openMenu: "Abrir menú", accountMenu: "Abrir menú de cuenta", signOutTitle: "¿Cerrar sesión en el museo?", signOutDescription: "Tu carrito y datos permanecerán guardados de forma segura." },
  fr: { collections: "Collections", marketplace: "Marché", about: "À propos", assets: "Vos ressources", upload: "Téléverser", support: "Questions et avis", moderate: "Examiner les dépôts", signIn: "Se connecter", signOut: "Se déconnecter", enterVr: "Entrer en VR", search: "Rechercher des objets", searchPlaceholder: "Rechercher des objets, matériaux ou collections…", searching: "Recherche…", noResults: "Aucun objet trouvé.", account: "Membre du musée", mobileAccount: "Compte mobile", language: "Langue", closeMenu: "Fermer le menu", openMenu: "Ouvrir le menu", accountMenu: "Ouvrir le menu du compte", signOutTitle: "Se déconnecter du musée ?", signOutDescription: "Votre panier et vos données resteront enregistrés en sécurité." },
  de: { collections: "Sammlungen", marketplace: "Marktplatz", about: "Über uns", assets: "Ihre Objekte", upload: "Hochladen", support: "Fragen und Feedback", moderate: "Uploads prüfen", signIn: "Anmelden", signOut: "Abmelden", enterVr: "VR betreten", search: "Artefakte suchen", searchPlaceholder: "Artefakte, Materialien oder Sammlungen suchen…", searching: "Suche…", noResults: "Keine Artefakte gefunden.", account: "Museumsmitglied", mobileAccount: "Mobilkonto", language: "Sprache", closeMenu: "Menü schließen", openMenu: "Menü öffnen", accountMenu: "Kontomenü öffnen", signOutTitle: "Vom Museum abmelden?", signOutDescription: "Warenkorb und Kontodaten bleiben sicher gespeichert." },
  ar: { collections: "المجموعات", marketplace: "السوق", about: "حول", assets: "مقتنياتك", upload: "رفع", support: "الاستفسارات والملاحظات", moderate: "مراجعة الرفع", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", enterVr: "دخول الواقع الافتراضي", search: "البحث عن القطع", searchPlaceholder: "ابحث عن القطع أو المواد أو المجموعات…", searching: "جارٍ البحث…", noResults: "لم يتم العثور على قطع.", account: "عضو المتحف", mobileAccount: "حساب جوال", language: "اللغة", closeMenu: "إغلاق القائمة", openMenu: "فتح القائمة", accountMenu: "فتح قائمة الحساب", signOutTitle: "تسجيل الخروج من المتحف؟", signOutDescription: "ستظل سلتك وبيانات حسابك محفوظة بأمان." },
  zh: { collections: "馆藏", marketplace: "市场", about: "关于", assets: "您的资产", upload: "上传", support: "咨询与反馈", moderate: "审核上传", signIn: "登录", signOut: "退出登录", enterVr: "进入 VR", search: "搜索文物", searchPlaceholder: "搜索文物、材料或馆藏…", searching: "正在搜索…", noResults: "未找到文物。", account: "博物馆会员", mobileAccount: "手机账户", language: "语言", closeMenu: "关闭菜单", openMenu: "打开菜单", accountMenu: "打开账户菜单", signOutTitle: "退出博物馆？", signOutDescription: "您的购物车和账户数据将被安全保存。" },
  ja: { collections: "コレクション", marketplace: "マーケット", about: "概要", assets: "あなたの資産", upload: "アップロード", support: "お問い合わせ・ご意見", moderate: "投稿を審査", signIn: "ログイン", signOut: "ログアウト", enterVr: "VRに入る", search: "文化財を検索", searchPlaceholder: "文化財、素材、コレクションを検索…", searching: "検索中…", noResults: "文化財が見つかりません。", account: "博物館メンバー", mobileAccount: "モバイルアカウント", language: "言語", closeMenu: "メニューを閉じる", openMenu: "メニューを開く", accountMenu: "アカウントメニューを開く", signOutTitle: "ログアウトしますか？", signOutDescription: "カートとアカウント情報は安全に保存されます。" },
  ko: { collections: "컬렉션", marketplace: "마켓", about: "소개", assets: "내 자산", upload: "업로드", support: "문의 및 의견", moderate: "업로드 검토", signIn: "로그인", signOut: "로그아웃", enterVr: "VR 입장", search: "유물 검색", searchPlaceholder: "유물, 재료 또는 컬렉션 검색…", searching: "검색 중…", noResults: "유물을 찾을 수 없습니다.", account: "박물관 회원", mobileAccount: "모바일 계정", language: "언어", closeMenu: "메뉴 닫기", openMenu: "메뉴 열기", accountMenu: "계정 메뉴 열기", signOutTitle: "박물관에서 로그아웃할까요?", signOutDescription: "장바구니와 계정 정보는 안전하게 보관됩니다." },
} as const;
